source 'https://rubygems.org'

gem 'oauth2'
gem 'rest-client'
gem 'active_support'
gem 'hashie'
gem 'httmultiparty'
gem 'trollop'
gem 'highline'
gem 'mail'
gem 'oj'
gem 'faker', :path=>'../forks/faker'
