source 'https://rubygems.org'

gem 'oauth2'
gem 'rest-client'
gem 'hashie'
gem 'httmultiparty'
gem 'trollop'
gem 'highline'
gem 'mail'
gem 'oj'
gem 'pry-plus'

gem 'faker',             github: 'nathanstitt/faker'
gem 'stockor-core',      github: "argosity/stockor-core",      branch: 'master'
gem "stockor-api",       github: "argosity/stockor-api",       branch: 'master'
gem "stockor-access",    github: "argosity/stockor-access",    branch: 'master'
gem "stockor-workspace", github: "argosity/stockor-workspace", branch: 'master'
