#!/usr/bin/env ruby

require 'i18n'
require 'rubygems'
require 'bundler'
Bundler.setup(:default)

require_relative 'lib/demo_data'

lb = Stockor.from_command_line( {
        :server=>'demo.ledgerbuddy.dev'
    })

DemoData.run( lb )
